### PR TITLE
Attempt to implement level gap

### PR DESCRIPTION
**Pull request by hellbringer616**
**PREFACE:**
So i have never; not once in my life; written any java; really any code unless HOCON counts (it doesn't)

This is probably a poor copy paste job; and i'm not sure if it will even work, and i am sure there is much more that needs to be changed.. But i am trying to help :)

this pull request is not even close to being able to be merged; as i am sure you know lol.

**_Pull Request:_**
Anyway, the goal of this is to implement a level gap as explained in #47 

I believe; if i am reading this correctly; that this sets up the variable/Configurable settings levelGap in the SkillTree.conf which will be called on... somewhere... If you can point me in the right direction i'd love to try and figure out how to implement this (so long as you don't mind answering my questions of course)

_On a somewhat unrelated note..._ Do you know how i can rebase using the online Github site? I am 20 commits behind and want to get everything back on par.

### CODE REVIEW

**Comment by NeumimTo** [comment]
You cannot rebase via github site, or at least theres no way im aware of.
Well in fact only thing i know which will work is to delete your fork and create a new fork again, eh.
Now you have to assign data to the variable. Skilltree loading is done in the class SkillTreeDAO, more specifically the method loadSkills.

If this wont scare you :D then next step will be in CharacterService, method upgradeSkill, where is decieded if the player can upgrade specific skill.

**Comment by NeumimTo** [comment]
Also this wont compile. 
You declared a variable called "levelGap", 
But then you are referencing it as "LevelGap". you have to lowercase the "L" symbol

**Comment by hellbringer616** [comment]
Fixed the upper case issues.

I'll Rebase with GitHub Desktop and recreate my changes there; seems i can't edit a file on Github Online without creating new pull requests for each one :P

**Comment by NeumimTo** [comment]
Implemented in 55a5413

**Pull request closed without merging**
